# -*- coding: utf-8 -*-
"""numpy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jZv0Rz2RfjHKkTMXFSPYHNvDP-pZtfk_
"""

import numpy as np

"""Numpy to biblioteka służąca do operacji na macierzach"""

a = np.arange(15).reshape(3, 5)
print(a)

print("a size is {}".format(a.shape))
print('\n')

b = a.reshape(5,3)
print(b)
print('\n')


zero_matrix = np.zeros((2,3))
print(zero_matrix)
print('\n')
one_matrix = np.ones((4,2))
print(one_matrix)

"""Podstawowe operacje na macierzach:"""

A = np.array( [[1,1],
               [0,1]] )
print("A")
print(A)
print('\n')

B = np.array( [[2,0],
               [3,4]] )

print("B")
print(B)
print('\n')

print('B\'')
print(B.T)
print('\n')

print("A * B")
print(A * B)
print('\n')

print("A x B")
print(A.dot(B))
print('\n')

print("B x A")
print(B.dot(A))
print('\n')

print("A - B")
print(A-B)
print('\n')

print("A + B")
print(A+B)
print('\n')

print("A + 3")
print(A+3)
print('\n')

print("B^2")
print(B*2)
print('\n')

"""### Zadanie

Korzystając z powyższych informacji  i mnożenia macieży skonstruować "tabliczkę mnożenia".
"""

